[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "cd frontend && npm ci",
    "cd backend && npm ci",
    "npm ci"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[phases.start]
cmd = "cd backend && node server.js" 